import assert from 'node:assert/strict';
import {build} from 'esbuild';
const code=(await build({entryPoints:['src/lib/drafts.ts'],bundle:true,write:false,platform:'node',format:'esm'})).outputFiles[0].text;
const {draftRecord,putDraft,listDrafts,removeDraft,draftId}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const records=new Map();let quotaFailure=false,closed=0;
globalThis.indexedDB={open(){const request={};queueMicrotask(()=>{request.result={createObjectStore(){},close(){closed++;},transaction(name,mode){const tx={error:null,objectStore(){const run=fn=>{const r={};queueMicrotask(()=>{if(quotaFailure&&mode==='readwrite'){tx.error=Error('QuotaExceededError');tx.onabort?.();return;}r.result=fn();tx.oncomplete?.();});return r;};return {put:value=>run(()=>{records.set(value.id,value);return value.id;}),delete:id=>run(()=>records.delete(id)),getAll:()=>run(()=>[...records.values()])};}};return tx;}};request.onupgradeneeded?.();request.onsuccess?.();});return request;}};
const inventory=Object.fromEntries(['skill','egg','mount','potion'].map(g=>[g,{amount:'',level:'',progress:'',target:'',selected:'',extra:'0'}]));inventory.potion.amount='0';
const photo=new File([new Uint8Array([137,80,78,71,1,2,3,4])],'capture.png',{type:'image/png'});
const value={nickname:'Member',inventory,changedFields:{potion:['amount']},files:{potion:photo},photos:{skill:'existing-photo-id'},saveMode:'partial',password:'not-stored',accessKey:'not-stored',adminToken:'not-stored'};
const one=draftRecord('clan-a',value),two=draftRecord('clan-b',value);
for(const secret of ['password','accessKey','adminToken'])assert.equal(secret in one,false);
assert.equal(one.inventory.potion.amount,'0');assert.equal(one.files.potion,photo);assert.equal(one.photos.skill,'existing-photo-id');
await Promise.all([putDraft(one),putDraft(two)]);
assert.equal((await listDrafts('clan-a')).length,1);assert.equal((await listDrafts('clan-a'))[0].files.potion.size,photo.size);assert.deepEqual([...new Uint8Array(await (await listDrafts('clan-a'))[0].files.potion.arrayBuffer())],[137,80,78,71,1,2,3,4]);
const updated=draftRecord('clan-a',{...value,inventory:{...inventory,potion:{...inventory.potion,amount:'943'}}});await Promise.all([putDraft(one),putDraft(updated)]);assert.equal((await listDrafts('clan-a'))[0].inventory.potion.amount,'943');
quotaFailure=true;await assert.rejects(()=>putDraft(one),/QuotaExceededError/);quotaFailure=false;assert.equal((await listDrafts('clan-a'))[0].inventory.potion.amount,'943');
await removeDraft(draftId('clan-a','Member'));assert.equal((await listDrafts('clan-a')).length,0);assert.equal((await listDrafts('clan-b')).length,1);assert.ok(closed>0);
globalThis.indexedDB=undefined;await assert.rejects(()=>listDrafts('clan-a'),/임시 보관/);
console.log('Drafts preserve photos, zeros and changed fields; exclude credentials; isolate clans; serialize writes; recover after quota failure.');
