import PhotoPreview from './PhotoPreview';
import {sortResources,nextResourceSort,type ResourceSort} from './lib/roster-sort';
import {draftRecord,putDraft,listDrafts,removeDraft,draftId,type Draft} from './lib/drafts';
import {t,tr,useLanguage,getLanguage} from './lib/i18n';
import ClanPortal from './ClanPortal';
import ScanDiagnostics from './ScanDiagnostics';
import {ScanFailure,type ScanReport} from './lib/scan-diagnostics';
import OcrCheck from './OcrCheck';
import {ascensionStatus} from '@/lib/summon-status';
import {getRecords,saveInventory,photoUrl,googleEnabled,unlockGoogle,leaveClan,activeClanName,activeClanId,checkSaveConnection,savedAccessKey,invitedKey} from './lib/api';
import {useEffect,useState,useRef} from 'react';
import {imageFromTransfer,normalizePhoto,maximumPhotoBytes,readScreenshot} from '@/lib/photo-input';
import {Camera,Package,ShieldCheck,RefreshCw,Upload,Check,Plus,Eye,Crown} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {groups,titles,photoTitles,emptyInventory,totalMerge,quantity,approximate,validateInventory,incompleteGroups,photoKinds,type Group,type Item,type Inventory,type PhotoKind,type ChangedFields} from '@/lib/inventory';
import {scanScreen,groupFor,regions} from '@/lib/screen-ocr';
type Row={nickname:string;details:Inventory;photos:Partial<Record<PhotoKind,string>>;updated_at:string};
const fmt=(n:number|null)=>n===null?t("미입력"):n.toLocaleString(getLanguage()==='en'?'en-US':'ko-KR');
const amountText=(s:string)=>quantity(s)===null?t("미입력"):(approximate(s)?t("약 "):'')+fmt(quantity(s));
function ResourceAmount({group,item}:{group:Group;item:Item}){
 const waiting=group!=='potion'&&ascensionStatus(item.level)==='승천대기';
 return <span className="resource-amount">{amountText(item.amount)}{waiting&&<span className="ascension-crown" role="img" aria-label={t("승천대기")} title={`${t("승천대기")} · ${t("승천 추천 재화량: 60k(60,000개) 이상")}`}><Crown size={16} aria-hidden="true"/></span>}</span>;
}
function PhotoUpload({kind,file,existing,busy,onUpload}:{kind:PhotoKind;file?:File;existing?:string;busy:boolean;onUpload:(file:File,kind:PhotoKind,fresh?:boolean)=>void}){
 const [url,setUrl]=useState(''),[pasteError,setPasteError]=useState(''),[reading,setReading]=useState(false);useEffect(()=>{if(!file){let active=true;setUrl('');if(existing)photoUrl(existing).then(u=>{if(active)setUrl(u);}).catch(console.error);return()=>{active=false;};}const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file,existing]);
 return <div className="photo-slot" data-photo-kind={kind} tabIndex={0} aria-label={t(photoTitles[kind])+t(" · 캡처 붙여넣기")} onPointerDown={e=>{if(!(e.target as HTMLElement).closest("button,input"))e.currentTarget.focus();}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect=busy?'none':'copy';}} onDrop={e=>{e.preventDefault();if(busy)return;const image=imageFromTransfer(e.dataTransfer);if(image){setPasteError('');onUpload(image,kind);}else setPasteError(t("JPG, PNG, WEBP 캡처 파일을 놓아주세요."));}}>
 {url?<div className="upload has-photo"><PhotoPreview src={url} alt={t(photoTitles[kind])}/><label className="replace" htmlFor={'photo-'+kind}><Camera size={16}/> {t(photoTitles[kind])} {t(" 바꾸기")}</label></div>:<label className="upload" htmlFor={'photo-'+kind}><Upload size={24}/><strong>{t(photoTitles[kind])} {t(" 올리기")}</strong><span>{t("캡처 파일 선택 · 끌어놓기 · Ctrl+V")}</span><small>{t("JPG · PNG · WEBP / 최대 10MB")}</small></label>}<input className="sr-only" id={'photo-'+kind} type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f){setPasteError('');onUpload(f,kind);}e.target.value='';}}/>
 <button type="button" className="capture-paste" disabled={busy||reading} onClick={async()=>{setPasteError('');setReading(true);try{onUpload(await readScreenshot(),kind);}catch(e){setPasteError(e instanceof Error?e.message:t("캡처를 붙여넣지 못했습니다."));}finally{setReading(false);}}}><Camera size={16}/>{reading?t("캡처 확인 중…"):t("복사한 캡처 붙여넣기")}</button>{file&&<button type="button" className="capture-paste" disabled={busy||reading} onClick={()=>onUpload(file,kind,true)}><RefreshCw size={16}/> {t(" 이 사진 다시 인식")}</button>}<p className="helper">{t("이 사진 칸을 선택하고 Ctrl+V로 붙여넣어도 자동 인식돼요.")}</p>{pasteError&&<p className="helper" role="alert">{t(pasteError)}</p>}</div>;
}
function Evidence({id,kind}:{id:string;kind:PhotoKind}){const [url,setUrl]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);return <div><button type="button" className="quiet" disabled={loading} onClick={async()=>{if(url){setUrl('');return;}setLoading(true);setError('');try{setUrl(await photoUrl(id));}catch(e){setError(e instanceof Error?e.message:t("사진 조회 실패"));}finally{setLoading(false);}}}><Eye size={15}/>{t(photoTitles[kind])} {loading?t("불러오는 중…"):url?t("닫기"):t("보기")}</button>{error&&<p role="alert">{t(error)}</p>}{url&&<PhotoPreview src={url} alt={t(photoTitles[kind])}/>}</div>;}
function NumberField({label,value,onChange,unit=''}:{label:string;value:string;onChange:(s:string)=>void;unit?:string}){return <label className="number-field"><span>{label}{unit&&<small>{unit}</small>}</span><input inputMode="numeric" type="number" min="0" max="1000000000000" step="1" placeholder={t("미입력")} value={value} onChange={e=>onChange(e.target.value)}/></label>;}
function Editor({group,item,patch,files,photos,busy,onUpload}:{group:Group;item:Item;patch:(key:keyof Item,value:string)=>void;files:Partial<Record<PhotoKind,File>>;photos:Partial<Record<PhotoKind,string>>;busy:boolean;onUpload:(f:File,k:PhotoKind,fresh?:boolean)=>void}){
 const kind=group as PhotoKind;const mergeKind=(group+'Merge') as PhotoKind;
 return <><PhotoUpload kind={kind} file={files[kind]} existing={photos[kind]} busy={busy} onUpload={onUpload}/><label className="field-label">{group==='potion'?t("녹색 물약 수량"):t("보유 소환 재화")}<input inputMode="decimal" placeholder={t("예: 35.8k 또는 35800")} value={item.amount} onChange={e=>patch('amount',e.target.value)}/></label><p className="helper">{item.amount&&quantity(item.amount)!==null?tr`${amountText(item.amount)}개${approximate(item.amount)?t(" · 사진의 축약 표시를 그대로 저장합니다."):''}`:t("사진에서 읽은 값은 등록 전에 확인해주세요.")}</p>
 {group!=='potion'&&<><div className="level-fields"><NumberField label={t("소환 레벨")} value={item.level} onChange={s=>patch('level',s)}/>{item.level!=='100'&&<><NumberField label={t("현재 단계")} value={item.progress} onChange={s=>patch('progress',s)}/></>}</div><p className="helper">{t("승천 상태: ")}{t(ascensionStatus(item.level))}</p>{item.level==='100'&&<p className="helper">{t("승천 추천 재화량: 60k(60,000개) 이상")}</p>}</>}
 {(group==='egg'||group==='mount')&&<section className="merge-section"><h3>{t("합성 수량")}</h3><PhotoUpload kind={mergeKind} file={files[mergeKind]} existing={photos[mergeKind]} busy={busy} onUpload={onUpload}/><div className="merge-fields"><NumberField label={t("사진 선택 수량")} value={item.selected} onChange={s=>patch('selected',s)}/><NumberField label={t("추가 수량 (+α)")} value={item.extra} onChange={s=>patch('extra',s)}/></div><p className="helper">{t("사진의 ‘선택됨’ 숫자에 포함되지 않은 수량만 추가하세요.")}</p><div className="merge-total"><span>{t("합성 합계")}</span><strong>{fmt(totalMerge(item))}<small>{t("개")}</small></strong></div></section>}
 </>;
}
function Home(){
 const [clanName,setClanName]=useState(activeClanName);
 const [diagnostics,setDiagnostics]=useState<ScanReport>();
 const [allRecords,setRecords]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [resourceSort,setResourceSort]=useState<ResourceSort>(null);
 const records=sortResources(allRecords,resourceSort);
 const [nickname,setNickname]=useState(''),[password,setPassword]=useState(''),[inventory,setInventory]=useState(emptyInventory);
 const [files,setFiles]=useState<Partial<Record<PhotoKind,File>>>({}),[photos,setPhotos]=useState<Partial<Record<PhotoKind,string>>>({});
 const changedFields=useRef<ChangedFields>({});
 const [saveMode,setSaveMode]=useState<'all'|'partial'>('all');
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[saving,setSaving]=useState(false),[tab,setTab]=useState<Group>('skill'),[detail,setDetail]=useState<Row|null>(null);
 const [drafts,setDrafts]=useState<Draft[]>([]),[draftStatus,setDraftStatus]=useState(''),[connectionStatus,setConnectionStatus]=useState(''),[checkingConnection,setCheckingConnection]=useState(false);
 const draftTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),draftEpoch=useRef(0);
 function draftSnapshot(){return draftRecord(activeClanId,{nickname,inventory,changedFields:changedFields.current,files,photos,saveMode});}
 async function keepDraft(){clearTimeout(draftTimer.current);const snapshot=draftSnapshot();await putDraft(snapshot);setDraftStatus(t("이 기기에 임시 보관했습니다. 서버 등록은 아직 완료되지 않았습니다."));setDrafts(await listDrafts(activeClanId));return snapshot.id;}
 useEffect(()=>{let live=true;listDrafts(activeClanId).then(values=>{if(live)setDrafts(values);}).catch(()=>{if(live)setDraftStatus(t("임시 보관을 사용할 수 없습니다. 이 화면을 닫기 전에 서버에 저장해주세요."));});return()=>{live=false;};},[]);
 useEffect(()=>{
  clearTimeout(draftTimer.current);const epoch=++draftEpoch.current;
  if(saving||(!Object.values(changedFields.current).some(keys=>keys.length)&&!Object.keys(files).length))return;
  const snapshot=draftSnapshot();setDraftStatus(t("입력 내용을 이 기기에 임시 보관 중…"));
  draftTimer.current=setTimeout(()=>{putDraft(snapshot).then(async()=>{const values=await listDrafts(activeClanId);if(draftEpoch.current===epoch){setDrafts(values);setDraftStatus(t("이 기기에 임시 보관했습니다. 서버 등록은 아직 완료되지 않았습니다."));}}).catch(()=>{if(draftEpoch.current===epoch)setDraftStatus(t("임시 보관에 실패했습니다. 저장 공간을 확인하고 화면을 닫지 마세요."));});},500);
  return()=>clearTimeout(draftTimer.current);
 },[nickname,inventory,files,photos,saveMode,busy,saving]);
 async function restoreDraft(draft:Draft){if(busy||saving)return;try{if(Object.keys(files).length||Object.values(changedFields.current).some(keys=>keys.length)){await keepDraft();draft=(await listDrafts(activeClanId)).find(d=>d.id===draft.id)||draft;}clearTimeout(draftTimer.current);++draftEpoch.current;setNickname(draft.nickname);setInventory(structuredClone(draft.inventory));changedFields.current=structuredClone(draft.changedFields);setFiles(draft.files);setPhotos(draft.photos);setSaveMode(draft.saveMode);setPassword('');setError('');setConnectionStatus('');setNotice(t("임시 보관 내용을 불러왔습니다. 비밀번호를 다시 입력하고 서버에 저장해주세요."));}catch{setError(t("현재 입력을 임시 보관하지 못해 불러오기를 중단했습니다."));}}
 async function reconnect(){setCheckingConnection(true);setConnectionStatus(t("저장 연결 확인 중…"));try{await checkSaveConnection();setConnectionStatus(t("저장 연결이 준비됐습니다. 비밀번호를 입력하고 저장 버튼을 눌러주세요."));}catch(e){setConnectionStatus(e instanceof Error?t(e.message):t("저장 연결을 확인하지 못했습니다. 잠시 후 다시 시도해주세요."));}finally{setCheckingConnection(false);}}
 async function refresh(){setLoading(true);try{const rows=await getRecords();setClanName(activeClanName);setRecords(rows.map((r:Row)=>({...r,details:{...emptyInventory(),...r.details}})));setError('');}catch(e){setError(e instanceof Error?e.message:t("현황을 불러오지 못했습니다."));}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_clan_resources',description:t("클랜원이 등록한 재화·소환 레벨·합성 수량을 읽습니다."),inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(){return {records:await getRecords()};}},{signal:lifecycle.signal})).catch(console.error);return()=>lifecycle.abort();},[]);
 function patch(g:Group,key:keyof Item,value:string){changedFields.current[g]=Array.from(new Set([...(changedFields.current[g]||[]),key]));setInventory(v=>({...v,[g]:{...v[g],[key]:value}}));}
 const uploading=useRef(false);
 async function upload(file:File,kind:PhotoKind,fresh=false){
 if(uploading.current||saving)return;
 setError('');setNotice('');setDiagnostics(undefined);const normalized=normalizePhoto(file);if(!normalized||file.size>maximumPhotoBytes){setError(t("IMG-02 · 사진은 JPG, PNG, WEBP로 10MB 이하로 올려주세요."));return;}file=normalized;uploading.current=true;
 setFiles(v=>({...v,[kind]:file}));setBusy(true);setProgress(0);const g=groupFor(kind);
 setInventory(v=>{const next={...v[g]};for(const r of regions[kind])if(r.field==='ratio'){next.progress='';next.target='';}else next[r.field]='';return {...v,[g]:next};});
 try{const result=await scanScreen(file,kind,setProgress,fresh);setDiagnostics(result.diagnostics);changedFields.current[g]=Array.from(new Set([...(changedFields.current[g]||[]),...Object.keys(result.item) as (keyof Item)[]]));setInventory(v=>({...v,[g]:{...v[g],...result.item}}));if(result.diagnostics.issues.length)setError(result.diagnostics.issues.map(i=>`${i.code} · ${t(photoTitles[kind])}: ${t(i.message)}`).join(' / '));else setNotice(tr`${t(photoTitles[kind])}를 읽었습니다. 수량과 레벨을 사진과 비교해주세요.`);}catch(e){if(e instanceof ScanFailure)setDiagnostics(e.report);setError(e instanceof ScanFailure?e.message:t("OCR-05 · 사진 인식 처리 중 오류가 발생했습니다."));}finally{uploading.current=false;setBusy(false);}
 }
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy||saving||uploading.current)return;setError('');setNotice('');try{if(saveMode==='all'){const missing=incompleteGroups(inventory);if(missing.length){setTab(missing[0]);throw Error(tr`${missing.map(g=>t(titles[g])).join(' · ')}에 미입력 값이 있습니다. 사진을 다시 인식한 뒤 전체 저장해주세요.`);}}for(const g of ['egg','mount'] as const)if(files[(g+'Merge') as PhotoKind]&&inventory[g].selected==='')throw Error(tr`${t(titles[g])} 합성 사진의 수량을 아직 읽지 못했습니다. 다시 인식해주세요.`);validateInventory(inventory);}catch(e){setError(e instanceof Error?e.message:t("입력값을 확인해주세요."));return;}setSaving(true);let keptDraft:string|undefined;try{try{keptDraft=await keepDraft();}catch{setDraftStatus(t("임시 보관에 실패했습니다. 저장 공간을 확인하고 화면을 닫지 마세요."));}const d=await saveInventory(nickname,password,inventory,files,changedFields.current);clearTimeout(draftTimer.current);++draftEpoch.current;changedFields.current={};if(keptDraft)try{await removeDraft(keptDraft);setDrafts(await listDrafts(activeClanId));setDraftStatus(t("서버 등록 완료 · 해당 임시 보관본을 정리했습니다."));}catch{setDraftStatus(t("서버 등록은 완료됐지만 임시 보관본 정리를 확인하지 못했습니다."));}if(d.details)setInventory(d.details);if(d.photos){setPhotos(d.photos);setFiles({});}await refresh();setNotice(tr`${nickname}님의 ${saveMode==='all'?t("스킬·알·탈것·물약 전체 재화"):t("입력한 재화")}를 저장했습니다.`);setPassword('');}catch(e){setError('SAVE-01 · '+(e instanceof Error?e.message:t("저장 실패")));}finally{setSaving(false);}}
 async function edit(row:Row){if(busy||saving)return;try{if(Object.keys(files).length||Object.values(changedFields.current).some(keys=>keys.length))await keepDraft();}catch{setError(t("현재 입력을 임시 보관하지 못해 불러오기를 중단했습니다."));return;}clearTimeout(draftTimer.current);++draftEpoch.current;changedFields.current={};setDraftStatus('');setConnectionStatus('');setSaveMode('partial');setNickname(row.nickname);setInventory(structuredClone(row.details));setPhotos(row.photos);setFiles({});setPassword('');setDetail(null);setNotice(t("수정 비밀번호를 입력한 뒤 변경한 내용을 등록해주세요."));document.getElementById('registration')?.scrollIntoView({behavior:'smooth'});}
 const missing=incompleteGroups(inventory);
 const totals=groups.map(g=>records.reduce((sum,r)=>sum+(quantity(r.details[g].amount)||0),0));
 return <main onPaste={e=>{if(detail)return;const image=imageFromTransfer(e.clipboardData);if(!image)return;e.preventDefault();const slot=(e.target as HTMLElement).closest('[data-photo-kind]'),kind=slot?.getAttribute('data-photo-kind');void upload(image,photoKinds.includes(kind as PhotoKind)?kind as PhotoKind:tab);}}><header className="topbar"><a className="brand" href={import.meta.env.BASE_URL}><span className="brand-icon"><Package size={23}/></span><span>{t("클랜 재화관리 ")}<small>{t("포지마스터")}</small></span></a><span className="clan-badge"><ShieldCheck size={15}/> {clanName.replace(/^우리 클랜$/,t("우리 클랜")).replace(/^서버 /,t("서버 "))} {googleEnabled&&<button className="quiet" onClick={leaveClan}>{t("나가기")}</button>}</span></header><div className="workspace">
 <section className="page-heading"><div><p className="eyebrow">CLAN INVENTORY</p><h1>{t("함께 모으는 재화 현황")}</h1><p>{t("사진을 올리고 확인한 수량을 공유하세요.")}</p></div><button className="quiet" onClick={refresh} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{t("현황 새로고침")}</button></section>
 <div className="summary">{groups.map((g,i)=><article key={g}><span className={'resource-marker marker-'+i}>{['S','E','M','P'][i]}</span><div><p>{t(titles[g])} {g==='potion'?'':t("소환 ")}{t("재화")}</p><strong>{records.some(r=>approximate(r.details[g].amount))&&<span className="approx">{t("약 ")}</span>}{fmt(totals[i])}<small>{t("개")}</small></strong><span className="meta">{records.filter(r=>r.details[g].amount!=='').length}{t("명 입력")}</span></div></article>)}</div>
 <div className="merge-summary"><span>{t("알 합성 ")}<strong>{fmt(records.reduce((s,r)=>s+(totalMerge(r.details.egg)||0),0))}{t("개")}</strong></span><span>{t("탈것 합성 ")}<strong>{fmt(records.reduce((s,r)=>s+(totalMerge(r.details.mount)||0),0))}{t("개")}</strong></span><span>{t("등록한 클랜원 ")}<strong>{records.length}{t("명")}</strong></span></div>
 <div className="columns"><section className="panel registration" id="registration"><div className="panel-heading"><div><span className="eyebrow">MY RESOURCES</span><h2>{t("내 재화 등록")}</h2></div><span className="step-badge">{t("사진 · 확인 · 등록")}</span></div><form onSubmit={save}><label className="field-label" htmlFor="nickname">{t("게임 닉네임")}</label><input id="nickname" disabled={busy||saving} required maxLength={24} placeholder={t("게임에서 사용하는 닉네임")} value={nickname} onChange={e=>setNickname(e.target.value)}/>
 <section aria-label={t("임시 보관과 저장 연결")} className="draft-status"><p className="helper">{t("입력값과 사진은 이 기기·브라우저에 임시 보관됩니다. 비밀번호는 보관하지 않습니다. 브라우저 데이터를 지우거나 비공개 모드로 사용하면 복구되지 않을 수 있습니다.")}</p>{draftStatus&&<p role="status">{draftStatus}</p>}{drafts.length>0&&<details><summary>{t("임시 보관 불러오기")}</summary>{drafts.map(draft=><p key={draft.id}><button type="button" className="capture-paste" disabled={busy||saving} onClick={()=>void restoreDraft(draft)}>{draft.nickname||t("닉네임 미입력")} · {new Date(draft.updatedAt).toLocaleString(getLanguage()==='en'?'en-US':'ko-KR')} · {t("불러오기")}</button></p>)}</details>}<button type="button" className="capture-paste" disabled={busy||saving||checkingConnection} onClick={()=>void reconnect()}>{checkingConnection?t("연결 확인 중…"):t("저장 연결 다시 확인")}</button>{connectionStatus&&<p role="status">{connectionStatus}</p>}</section>
 <div className="save-mode" role="group" aria-label={t("저장 방식")}><button type="button" className={saveMode==='all'?'active':''} disabled={busy||saving} onClick={()=>setSaveMode('all')}>{t("전체 모아서 저장")}</button><button type="button" className={saveMode==='partial'?'active':''} disabled={busy||saving} onClick={()=>setSaveMode('partial')}>{t("일부 항목 저장")}</button></div><p className="helper">{saveMode==='all'?t("스킬 → 알 → 탈것 → 물약 순서로 사진을 올리세요. 탭을 바꿔도 입력한 내용은 유지됩니다."):t("변경한 항목만 저장합니다. 빈칸과 수정하지 않은 재화·사진은 기존 기록을 유지합니다.")}</p>
 <fieldset disabled={busy||saving} className="editor-fieldset"><Tabs value={tab} onValueChange={v=>setTab(v as Group)}><TabsList className="resource-tabs">{groups.map(g=><TabsTrigger key={g} value={g}>{g==='potion'?t("물약"):g==='egg'?t("알"):t(titles[g])}</TabsTrigger>)}</TabsList>{groups.map(g=><TabsContent key={g} value={g}><Editor group={g} item={inventory[g]} patch={(k,s)=>patch(g,k,s)} files={files} photos={photos} busy={busy||saving} onUpload={upload}/></TabsContent>)}</Tabs></fieldset>
 {diagnostics&&<ScanDiagnostics key={JSON.stringify(diagnostics)} report={diagnostics}/>}
 {busy&&<div className="scan-status" role="status"><span>{t("사진에서 숫자를 읽고 있습니다… ")}{progress}%</span><Progress value={progress}/></div>}
 {saveMode==='all'&&<button type="button" className="next-resource" disabled={busy||saving} onClick={()=>{const next=groups[groups.indexOf(tab)+1];if(next)setTab(next);else document.getElementById('save-review')?.scrollIntoView({behavior:'smooth',block:'center'});}}>{groups[groups.indexOf(tab)+1]?tr`다음: ${t(titles[groups[groups.indexOf(tab)+1]])} 사진 올리기`:t("전체 내역 확인하기")}</button>}
 <section className="save-review" id="save-review" aria-label={t("전체 저장 내역")}><h3>{t("한 번에 저장할 내역 ")}<small>{4-missing.length}{t("/4 항목 완료")}</small></h3>{groups.map(g=><button key={g} type="button" disabled={busy||saving} className={missing.includes(g)?'incomplete':''} onClick={()=>setTab(g)}><span><strong>{t(titles[g])}</strong><small>{g==='potion'?t("수량만 저장"):tr`${inventory[g].level||t("미입력")}레벨 · ${inventory[g].level==='100'?t("최대"):(inventory[g].progress||t("미입력"))+' '+t("단계")}`}{(g==='egg'||g==='mount')&&tr` · 합성 ${fmt(totalMerge(inventory[g]))}`}</small></span><span>{inventory[g].amount||t("미입력")}<small>{missing.includes(g)?t("확인 필요"):t("입력 완료")}</small></span></button>)}</section>
 <label className="field-label" htmlFor="password">{t("본인 수정 비밀번호")}</label><input id="password" disabled={busy||saving} type="password" minLength={6} maxLength={100} required autoComplete="off" placeholder={t("6자 이상 · 다음 수정 때도 사용")} value={password} onChange={e=>setPassword(e.target.value)}/><p className="helper">{t("처음 정한 비밀번호로 같은 닉네임의 재화를 수정합니다.")}</p>
 <button className="submit" type="submit" disabled={busy||saving}>{saving?t("저장 중…"):<><Check size={18}/>{saveMode==='all'?t("4종 재화 한 번에 저장"):t("입력한 재화 저장")}</>}</button><p className="helper center">{saveMode==='all'?t("네 종류의 재화와 올린 사진·합성 수량을 한 번에 저장합니다."):t("빈칸은 삭제하지 않습니다. 0을 입력하면 해당 수량만 0으로 수정됩니다.")}</p></form></section>
 <section className="panel roster"><div className="panel-heading"><div><span className="eyebrow">CLAN OVERVIEW</span><h2>{t("클랜원 재화 ")}<span className="count">{records.length}</span></h2></div><span className="meta" aria-live="polite">{resourceSort?`${t(titles[resourceSort.group])} · ${t(resourceSort.direction==='desc'?"내림차순":"오름차순")}`:t("최근 등록순")}</span></div>
 <div className="resource-sort" role="group" aria-label={t("재화 정렬")}><button type="button" className={!resourceSort?'active':''} aria-pressed={!resourceSort} onClick={()=>setResourceSort(null)}>{t("최근 등록순")}</button>{groups.map(g=><button key={g} type="button" className={resourceSort?.group===g?'active':''} aria-pressed={resourceSort?.group===g} onClick={()=>setResourceSort(current=>nextResourceSort(current,g))}>{t(g==='egg'?"알":g==='potion'?"녹색 물약":titles[g])} {resourceSort?.group===g?(resourceSort.direction==='desc'?`↓ ${t("내림차순")}`:`↑ ${t("오름차순")}`):'↕'}</button>)}</div><p className="sort-help">{t("재화 버튼을 다시 누르면 오름차순·내림차순이 전환됩니다. 미입력은 마지막에 표시합니다.")}</p>
 {loading&&records.length===0?<div className="empty">{t("현황을 불러오고 있습니다.")}</div>:records.length===0?<div className="empty"><span className="empty-icon"><Package size={35}/></span><h3>{t("첫 재화를 등록해주세요")}</h3><p>{t("클랜원이 올린 최신 수량이")}<br/>{t("이곳에 모이고 합계에 반영됩니다.")}</p></div>:<Table><TableHeader><TableRow><TableHead>{t("닉네임 / 등록일")}</TableHead><TableHead className="number">{t("스킬")}</TableHead><TableHead className="number">{t("알 재화 / 합성")}</TableHead><TableHead className="number">{t("탈것 재화 / 합성")}</TableHead><TableHead className="number">{t("물약")}</TableHead></TableRow></TableHeader><TableBody>{records.map(row=><TableRow key={row.nickname}><TableCell><button className="nickname" onClick={()=>setDetail(row)}>{row.nickname}</button><span className="date">{new Date(row.updated_at).toLocaleString(getLanguage()==='en'?'en-US':'ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span></TableCell>{groups.map(g=><TableCell key={g} className="number"><ResourceAmount group={g} item={row.details[g]}/>{(g==='egg'||g==='mount')&&<span className="date">{t("합성 ")}{fmt(totalMerge(row.details[g]))}</span>}</TableCell>)}</TableRow>)}</TableBody></Table>}
 <div className="roster-note"><ShieldCheck size={18}/><p>{t("닉네임을 누르면 소환 레벨·진행도·합성 내역과 사진을 볼 수 있어요.")}<br/>{t("k로 표시된 수량과 그 합계는 ‘약’으로 표시합니다.")}</p></div></section></div>
 {error&&<div className="message error" role="alert">{t(error)}</div>}{notice&&<div className="message success" role="status">{t(notice)}</div>}
 <footer>FORGE MASTER <span>{t("클랜 재화 현황 · ")}<a href={import.meta.env.BASE_URL+'#clans'}>{t("클랜장 관리")}</a></span></footer></div>
 <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="detail-sheet overflow-y-auto"><SheetHeader><SheetTitle>{detail?.nickname}{t("님의 재화")}</SheetTitle><SheetDescription>{t("개인별 최신 등록 현황")}</SheetDescription></SheetHeader>{detail&&<div className="detail-body">{groups.map(g=><section className="detail-group" key={g}><h3>{t(titles[g])}</h3><dl><div><dt>{t("보유 재화")}</dt><dd>{amountText(detail.details[g].amount)}{detail.details[g].amount&&<small>{t("원래 표시: ")}{detail.details[g].amount}</small>}</dd></div>{g!=='potion'&&<><div><dt>{t("소환 레벨")}</dt><dd>{detail.details[g].level||t("미입력")}</dd></div><div><dt>{t("승천 상태")}</dt><dd>{t(ascensionStatus(detail.details[g].level))}{detail.details[g].level==='100'&&<small>{t("승천 추천 재화량: 60k(60,000개) 이상")}</small>}</dd></div><div><dt>{t("현재 단계")}</dt><dd>{detail.details[g].level==='100'?t("최대"):detail.details[g].progress||t("미입력")}</dd></div></>}{(g==='egg'||g==='mount')&&<div><dt>{t("합성 수량")}</dt><dd>{fmt(totalMerge(detail.details[g]))}<small>{t("사진 ")}{detail.details[g].selected||t("미입력")} {t(" + 추가 ")}{detail.details[g].extra||'0'}</small></dd></div>}</dl></section>)}<div className="evidence-links">{photoKinds.filter(k=>detail.photos[k]).map(k=><Evidence key={k} id={detail.photos[k]!} kind={k}/>)}</div><button className="submit" disabled={busy||saving} onClick={()=>void edit(detail)}>{t("내 재화 수정하기")}</button></div>}</SheetContent></Sheet>
 </main>;
}

export default function App(){useLanguage();useEffect(()=>{const navigate=()=>location.reload();window.addEventListener('hashchange',navigate);return()=>window.removeEventListener('hashchange',navigate);},[]);const [ready,setReady]=useState(!googleEnabled),[key,setKey]=useState(()=>invitedKey||savedAccessKey()),[checking,setChecking]=useState(false),[error,setError]=useState('');async function enter(e?:React.FormEvent){e?.preventDefault();setChecking(true);setError('');try{await unlockGoogle(key);setReady(true);}catch(e){setError(e instanceof Error?e.message:t("연결 실패"));}finally{setChecking(false);}}if(location.hash==='#ocr-check')return <OcrCheck/>;if(location.hash==='#clans'||new URLSearchParams(location.hash.slice(1)).has('manage'))return <ClanPortal/>;if(ready)return <Home/>;return <main><div className="workspace" style={{maxWidth:500,paddingTop:64}}><section className="panel registration"><div className="panel-heading"><h1>{t("클랜 재화관리")}</h1></div><p>{invitedKey?t("초대 링크의 입장 코드가 입력되었습니다. 아래 버튼을 눌러 클랜에 들어가세요."):t("클랜장이 알려준 입장 코드를 입력해주세요.")}</p><form onSubmit={enter}><label className="field-label" htmlFor="clan-key">{t("클랜 입장 코드")}</label><input id="clan-key" type="password" autoComplete="off" required value={key} onChange={e=>setKey(e.target.value)} disabled={checking}/><button className="submit" disabled={checking}>{checking?t("연결 확인 중…"):t("클랜 현황 열기")}</button>{error&&<p role="alert">{t(error)}</p>}</form><p><a href={import.meta.env.BASE_URL+'#clans'}>{t("새 클랜 만들기 · 클랜장 관리")}</a></p></section></div></main>;}
