import {useState} from 'react';
import {clanAction,memberPasswordResetSupported} from './lib/api';
import {t} from './lib/i18n';

export default function MemberPasswordReset({clanId,adminToken,disabled}:{clanId:string;adminToken:string;disabled:boolean}){
 const [members,setMembers]=useState<string[]>([]),[loaded,setLoaded]=useState(false),[nickname,setNickname]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){if(busy||disabled)return;setBusy(true);setError('');setNotice('');try{const reply=await clanAction('adminMembers',{clanId,adminToken});setMembers(reply.members||[]);setLoaded(true);}catch(e){setError(e instanceof Error?e.message:t('회원 목록을 불러오지 못했습니다.'));}finally{setBusy(false);}}
 async function reset(e:React.FormEvent){e.preventDefault();if(busy||disabled||!confirmed)return;setError('');setNotice('');if(password!==confirmation){setError(t('새 비밀번호가 서로 다릅니다.'));return;}setBusy(true);try{await clanAction('resetMemberPassword',{clanId,adminToken,nickname,newPassword:password});setPassword('');setConfirmation('');setConfirmed(false);setNotice(nickname+' · '+t('수정 비밀번호를 변경했습니다. 기존 재화와 사진은 유지됩니다.'));}catch(e){setError(e instanceof Error?e.message:t('회원 비밀번호 변경 실패'));}finally{setBusy(false);}}
 return <section className="member-password-reset"><h3>{t('회원 수정 비밀번호 초기화')}</h3><p className="helper">{t('비밀번호를 잊은 회원의 본인 여부를 확인한 뒤 새 비밀번호를 정해주세요. 기존 재화·사진·등록일은 그대로 유지됩니다.')}</p>{!memberPasswordResetSupported?<p role="status">{t('회원 비밀번호 초기화는 구글 스크립트 업데이트 후 사용할 수 있습니다.')}</p>:<><button type="button" className="capture-paste" disabled={busy||disabled} onClick={()=>void load()}>{busy?t('처리 중…'):t('회원 목록 불러오기')}</button>{loaded&&<form onSubmit={reset}><label className="field-label">{t('초기화할 회원')}<select required disabled={busy||disabled} value={nickname} onChange={e=>{setNickname(e.target.value);setConfirmed(false);setPassword('');setConfirmation('');setNotice('');setError('');}}><option value="">{t('등록한 닉네임 선택')}</option>{members.map(name=><option key={name} value={name}>{name}</option>)}</select></label><label className="field-label">{t('새 수정 비밀번호')}<input required type="password" minLength={6} maxLength={100} autoComplete="new-password" disabled={busy||disabled} value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field-label">{t('새 비밀번호 확인')}<input required type="password" minLength={6} maxLength={100} autoComplete="new-password" disabled={busy||disabled} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><label className="reset-confirm"><input type="checkbox" required checked={confirmed} disabled={busy||disabled||!nickname} onChange={e=>setConfirmed(e.target.checked)}/>{nickname&&<strong>{nickname} · </strong>}{t('이 회원의 비밀번호를 변경하는 것이 맞습니다.')}</label><button type="submit" className="capture-paste" disabled={busy||disabled||!nickname||!confirmed||password.length<6||password!==confirmation}>{busy?t('처리 중…'):t('선택한 회원 비밀번호 변경')}</button><p className="helper">{t('변경 후 회원에게 새 비밀번호를 개인적으로 전달하세요. 회원은 기존 닉네임과 새 비밀번호로 내 재화를 불러오고 수정할 수 있습니다. 이전 비밀번호는 사용할 수 없습니다.')}</p></form>}</>}{error&&<p role="alert">{t(error)}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
