import {useState} from 'react';
import {googleEnabled,memberRecovery} from './lib/api';
import {t} from './lib/i18n';
export type RecoveryReceipt={nickname:string;code:string};
export default function MemberSelfRecovery({disabled,receipt,onReceipt}:{disabled:boolean;receipt?:RecoveryReceipt;onReceipt:(receipt?:RecoveryReceipt)=>void}){
 const [mode,setMode]=useState<'reset'|'issue'>('reset'),[name,setName]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[next,setNext]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[copied,setCopied]=useState(false);
 if(!googleEnabled)return null;
 function select(value:'reset'|'issue'){setMode(value);setPassword('');setCode('');setNext('');setConfirmation('');setError('');setNotice('');}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||disabled)return;setError('');setNotice('');if(mode==='reset'&&next!==confirmation){setError(t('새 비밀번호가 서로 다릅니다.'));return;}setBusy(true);try{const reply=await memberRecovery(mode==='issue'?'issueMemberRecovery':'recoverMemberPassword',mode==='issue'?{nickname:name,password}:{nickname:name,recoveryCode:code,newPassword:next});if(!reply.recoveryCode)throw Error(t('복구 코드를 확인하지 못했습니다.'));onReceipt({nickname:name.trim().normalize('NFKC'),code:reply.recoveryCode});setCopied(false);setPassword('');setCode('');setNext('');setConfirmation('');setNotice(t(mode==='issue'?'개인 복구 코드를 발급했습니다. 이전 복구 코드는 사용할 수 없습니다.':'비밀번호를 재설정했습니다. 새 비밀번호로 로그인하세요. 기존 재화와 사진은 유지됩니다.'));}catch(e){setError(e instanceof Error?e.message:t('비밀번호 재설정 실패'));}finally{setBusy(false);}}
 return <section className="member-password-reset self-recovery">{receipt&&<div className="recovery-receipt" role="status"><h3>{receipt.nickname} · {t('개인 복구 코드')}</h3><p className="helper">{t('비밀번호를 잊었을 때 필요한 본인 확인 코드입니다. 지금 복사해 안전한 곳에 보관하세요. 이 화면을 닫으면 다시 볼 수 없습니다. 다른 사람에게 공유하지 마세요.')}</p><code className="recovery-code">{receipt.code.match(/.{1,8}/g)?.join('-')}</code><button type="button" className="capture-paste" disabled={busy||disabled} onClick={async()=>{try{await navigator.clipboard.writeText(receipt.code);setCopied(true);}catch{setError(t('코드를 직접 선택해 복사해주세요.'));}}}>{copied?t('복사했습니다.'):t('복구 코드 복사')}</button><button type="button" className="capture-paste" disabled={busy||disabled} onClick={()=>{onReceipt(undefined);setCopied(false);}}>{t('보관 완료 · 코드 닫기')}</button></div>}<details><summary>{t('비밀번호를 잊으셨나요?')}</summary><div className="save-mode" role="group" aria-label={t('비밀번호 복구 작업')}><button type="button" disabled={busy||disabled} className={mode==='reset'?'active':''} onClick={()=>select('reset')}>{t('비밀번호 직접 재설정')}</button><button type="button" disabled={busy||disabled} className={mode==='issue'?'active':''} onClick={()=>select('issue')}>{t('복구 코드 발급·재발급')}</button></div><p className="helper">{t(mode==='reset'?'등록한 닉네임과 개인 복구 코드 또는 운영자 일회성 코드로 새 비밀번호를 설정합니다. 클랜 입장 비밀번호와는 별개입니다.':'현재 수정 비밀번호로 본인 확인 후 복구 코드를 발급합니다. 재발급하면 이전 코드는 무효가 됩니다.')}</p><p className="helper">{t('개인 복구 코드가 없는 기존 회원도 운영자가 발급한 일회성 코드로 복구할 수 있습니다. 운영자 코드는 한 번 사용하거나 10분이 지나면 무효가 됩니다.')}</p><form onSubmit={submit}><label className="field-label">{t('게임 닉네임')}<input required maxLength={24} autoComplete="username" disabled={busy||disabled} value={name} onChange={e=>setName(e.target.value)}/></label>{mode==='issue'?<label className="field-label">{t('현재 수정 비밀번호')}<input required type="password" minLength={6} maxLength={100} autoComplete="current-password" disabled={busy||disabled} value={password} onChange={e=>setPassword(e.target.value)}/></label>:<><label className="field-label">{t('개인 복구 코드 / 운영자 일회성 코드')}<input required type="password" maxLength={120} autoComplete="off" autoCapitalize="none" spellCheck={false} disabled={busy||disabled} value={code} onChange={e=>setCode(e.target.value)}/></label><label className="field-label">{t('새 수정 비밀번호')}<input required type="password" minLength={6} maxLength={100} autoComplete="new-password" disabled={busy||disabled} value={next} onChange={e=>setNext(e.target.value)}/></label><label className="field-label">{t('새 비밀번호 확인')}<input required type="password" minLength={6} maxLength={100} autoComplete="new-password" disabled={busy||disabled} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label></>}<button className="capture-paste" disabled={busy||disabled||!name.trim()||(mode==='reset'&&(!code.trim()||next.length<6||next!==confirmation))}>{busy?t('처리 중…'):t(mode==='issue'?'개인 복구 코드 발급':'새 비밀번호 설정')}</button></form></details>{error&&<p role="alert">{t(error)}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
