import {useState} from 'react';
import {issueOperatorRecoveryCode} from './lib/api';
import {t,useLanguage} from './lib/i18n';
export default function OperatorRecovery(){
 useLanguage();
 const [password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<{code:string;expires:number}>(),[copied,setCopied]=useState(false);
 async function issue(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setReceipt(undefined);setCopied(false);try{const r=await issueOperatorRecoveryCode(password);if(!r.recoveryCode||!r.expiresAt)throw Error(t('복구 코드를 확인하지 못했습니다.'));setReceipt({code:r.recoveryCode,expires:r.expiresAt});}catch(e){setError(e instanceof Error?e.message:t('비밀번호 재설정 실패'));}finally{setPassword('');setBusy(false);}}
 return <main><div className="workspace" style={{maxWidth:560,paddingTop:48}}><section className="panel registration"><div className="panel-heading"><h1>{t('운영자 일회성 복구 코드')}</h1></div><div style={{padding:24}}><p>{t('모든 클랜 회원의 수정 비밀번호 복구에 사용할 수 있습니다. 코드 하나는 한 명에게 한 번만 사용할 수 있고 10분 뒤 만료됩니다.')}</p><form onSubmit={issue}><label className="field-label">{t('운영자 복구 비밀번호')}<input required type="password" minLength={10} maxLength={100} autoComplete="off" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="submit" disabled={busy}>{busy?t('처리 중…'):t('일회성 복구 코드 발급')}</button></form><p className="helper">{t('새 코드를 발급하면 이전 운영자 코드는 무효가 됩니다. 복구할 회원마다 새 코드를 발급하세요.')}</p>{receipt&&<div className="recovery-receipt"><h3>{t('이번 복구 코드')}</h3><code className="recovery-code">{receipt.code.match(/.{1,8}/g)?.join('-')}</code><p>{t('만료 시각')}: {new Date(receipt.expires).toLocaleTimeString()}</p><button type="button" className="capture-paste" onClick={async()=>{try{await navigator.clipboard.writeText(receipt.code);setCopied(true);}catch{setError(t('코드를 직접 선택해 복사해주세요.'));}}}>{copied?t('복사했습니다.'):t('복구 코드 복사')}</button><p className="helper">{t('대상 클랜에 입장한 뒤 비밀번호를 잊으셨나요?에서 회원 닉네임·이 코드·새 비밀번호를 입력하세요. 다른 회원에게 전체 공지하지 마세요.')}</p><button type="button" className="capture-paste" onClick={()=>setReceipt(undefined)}>{t('코드 닫기')}</button></div>}{error&&<p role="alert">{t(error)}</p>}<p><a href={import.meta.env.BASE_URL}>{t('기존 클랜 입장으로 돌아가기')}</a></p></div></section></div></main>;
}
